# GitHub issue template chooser. For more information see:
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

blank_issues_enabled: true
contact_links:
  - name: Ask a question ‚ùì
    url: https://github.com/{{cookiecutter.github_org}}/{{cookiecutter.github_repo_name}}/discussions/new?category=support
    # TODO(cookiecutter): Make sure the GitHub repository has a discussion category "Support"
    # Rename the "Q&A" category to "Support" and change the emoji to üÜò (SOS)
    about: Use this if you are not sure how to do something, have installation problems, etc.
